export const mockArticles = [
  "ai/tech_selection_tips.md",
  "architecture/klearn_architecture_handson.md",
  "backend/scraping.md",
  "database/db_desgin.md",
  "database/unti_pattern.md",
  "devops/effective_devops.md",
  "event/Zenn,しずかなインターネット「どうやって開発したの？」開発者catnoseさんにきいてみた.md",
  "event/フロントエンドの技術選定 ~2023を振り返る~ Lunch LT.md",
  "event/フロントエンド技術選定 ~ゼロランタイムCSS in JSとTailwind CSS編~.md",
  "framework/nextjs/server_actions/mui_stepper_tips.md",
  "framework/nextjs/tech_selction_tips.md",
  "framework/rails/activerecord/create_with_child_record.md",
  "framework/rails/callback.md",
  "framework/rails/design/operate_multiple_resources.md",
  "framework/rails/gem/activerecord-import.md",
  "framework/rails/gem/enumerize.md",
  "framework/rails/routes.md",
  "framework/rails/scraping_with_selenium.md",
  "frontend/debug/responsive.md",
  "frontend/mui/email_link.md",
  "frontend/mui/useRef_for_textfield.md",
  "frontend/test/coverage.md",
  "frontend/test/integration_test.md",
  "frontend/test/jest_mock.md",
  "frontend/test/jest_unit_test.md",
  "frontend/test/testing_techniques_and_overview.md",
  "frontend/test/ui_component_test.md",
  "infrastructure/aws/dynamodb.md",
  "infrastructure/aws/loadBalancer.md",
  "lang/Golang/ATourOfGo/flow-control-statements.md",
  "lang/Golang/ATourOfGo/methods-and-interfaces.md",
  "lang/Golang/ATourOfGo/more-types.md",
  "lang/Golang/ATourOfGo/packages-variables-functions.md",
  "lang/Golang/LearningGo/Chapter1.md",
  "lang/Golang/LearningGo/Chapter2.md",
  "lang/Golang/LearningGo/Chapter3.md",
  "lang/Golang/LearningGo/Chapter4.md",
  "lang/Golang/LearningGo/Chapter5.md",
  "lang/JavaScript/class.md",
  "lang/JavaScript/diffArrowFunctionAndOther.md",
  "lang/JavaScript/this.md",
  "lang/TypeScript/type.md",
];

export const mockPathAndDateWithFrontMatters = [
  {
    path: "README.md",
    date: new Date("2024-09-25T14:59:34.000Z"),
    title: "",
    tags: [],
  },
  {
    path: "architecture/klearn_architecture_handson.md",
    date: new Date("2024-09-22T12:43:06.000Z"),
    title: "手を動かしてわかるクリーンアーキテクチャ",
    tags: ["アーキテクチャ", "テスト", "書籍"],
  },
  {
    path: "ai/tech_selection_tips.md",
    date: new Date("2024-09-18T16:18:13.000Z"),
    title: " 2024年 AIマイクロサービスのプロジェクト構成とLLM選定",
    tags: ["AI", "イベント"],
  },
  {
    path: "backend/scraping.md",
    date: new Date("2024-09-18T16:18:13.000Z"),
    title: "スクレイピングに関するTips",
    tags: ["スクレイピング", "tips"],
  },
  {
    path: "database/db_desgin.md",
    date: new Date("2024-09-18T16:18:13.000Z"),
    title: "達人に学ぶDB設計徹底指南書",
    tags: ["設計", "DB", "書籍"],
  },
  {
    path: "database/unti_pattern.md",
    date: new Date("2024-09-18T16:18:13.000Z"),
    title: "失敗から学ぶ RDBの正しい歩き方",
    tags: ["データベース", "書籍"],
  },
  {
    path: "devops/effective_devops.md",
    date: new Date("2024-09-18T16:18:13.000Z"),
    title: "Effective DevOps",
    tags: ["devops", "書籍"],
  },
  {
    path: "event/Zenn,しずかなインターネット「どうやって開発したの？」開発者catnoseさんにきいてみた.md",
    date: new Date("2024-09-18T16:18:13.000Z"),
    title:
      "Zenn,しずかなインターネット「どうやって開発したの？」開発者catnoseさんにきいてみた",
    tags: ["イベント", "個人開発"],
  },
  {
    path: "event/フロントエンドの技術選定 ~2023を振り返る~ Lunch LT.md",
    date: new Date("2024-09-18T16:18:13.000Z"),
    title: "フロントエンドの技術選定 ~2023を振り返る~ Lunch LT",
    tags: ["フロントエンド", "技術選定", "イベント"],
  },
  {
    path: "event/フロントエンド技術選定 ~ゼロランタイムCSS in JSとTailwind CSS編~.md",
    date: new Date("2024-09-18T16:18:13.000Z,"),
    title:
      "これからのスタイリング、どう向き合っていく？〜技術選定と事業成長の狭間で〜",
    tags: ["イベント", "CSS", "フロントエンド"],
  },
  {
    path: "framework/nextjs/server_actions/mui_stepper_tips.md",
    date: new Date("2024-09-18T16:18:13.000Z"),
    title: "MUI の Stepper で Server Actions を実行する際の注意点",
    tags: ["MUI", "Nextjs", "Tips"],
  },
  {
    path: "framework/nextjs/tech_selction_tips.md",
    date: new Date("2024-09-18T16:18:13.000Z"),
    title: "「手を動かしてわかるクリーンアーキテクチャ」のメモ",
    tags: ["イベント", "Nextjs", "技術選定"],
  },
  {
    path: "framework/rails/activerecord/create_with_child_record.md",
    date: new Date("2024-09-18T16:18:13.000Z"),
    title: "子レコードのデータも一緒に作成する場合の Tips",
    tags: ["Rails", "Tips"],
  },
  {
    path: "framework/rails/callback.md",
    date: new Date("2024-09-18T16:18:13.000Z"),
    title: "コールバック周りのTips",
    tags: ["Rails", "Tips"],
  },
  {
    path: "framework/rails/design/operate_multiple_resources.md",
    date: new Date("2024-09-18T16:18:13.000Z"),
    title: "Railsで複数リソースを一括操作する",
    tags: ["Rails", "Tips"],
  },
  {
    path: "framework/rails/gem/activerecord-import.md",
    date: new Date("2024-09-18T16:18:13.000Z"),
    title: "activerecord-importの`on_duplicate_key_update`オプションについて",
    tags: ["Rails"],
  },
  {
    path: "framework/rails/gem/enumerize.md",
    date: new Date("2024-09-18T16:18:13.000Z"),
    title: "enumerizeのメモ",
    tags: ["Rails"],
  },
  {
    path: "framework/rails/routes.md",
    date: new Date("2024-09-18T16:18:13.000Z"),
    title: "ルーティング周りのTips",
    tags: ["Rails", "Tips"],
  },
  {
    path: "framework/rails/scraping_with_selenium.md",
    date: new Date("2024-09-18T16:18:13.000Z"),
    title: "Seleniumを使ったスクレイピング",
    tags: ["Selenium", "Rails"],
  },
  {
    path: "frontend/debug/responsive.md",
    date: new Date("2024-09-18T16:18:13.000Z"),
    title: "スマホの実機でのデバッグする際のTips",
    tags: ["デバッグ", "フロントエンド", "Tips"],
  },
  {
    path: "frontend/mui/email_link.md",
    date: new Date("2024-09-18T16:18:13.000Z"),
    title: "MUIでメールリンクを作成する方法",
    tags: ["フロントエンド", "MUI", "Tips"],
  },
  {
    path: "frontend/mui/useRef_for_textfield.md",
    date: new Date("2024-09-18T16:18:13.000Z"),
    title: "TextFeildにuseRefを使う際の注意点",
    tags: ["フロントエンド", "React", "MUI"],
  },
  {
    path: "frontend/test/coverage.md",
    date: new Date("2024-09-18T16:18:13.000Z"),
    title: "フロントエンド開発のためのテスト入門 ~ カバレッジレポート ~",
    tags: ["フロントエンド", "テスト", "書籍"],
  },
  {
    path: "frontend/test/integration_test.md",
    date: new Date("2024-09-18T16:18:13.000Z"),
    title: "フロントエンド開発のためのテスト入門 ~ 統合テスト ~",
    tags: ["フロントエンド", "テスト", "書籍"],
  },
  {
    path: "frontend/test/jest_mock.md",
    date: new Date("2024-09-18T16:18:13.000Z"),
    title: "フロントエンド開発のためのテスト入門 ~ モック関連の用語の整理 ~",
    tags: ["フロントエンド", "テスト", "書籍"],
  },
  {
    path: "frontend/test/jest_unit_test.md",
    date: new Date("2024-09-18T16:18:13.000Z"),
    title: "フロントエンド開発のためのテスト入門 ~ 単体テスト ~",
    tags: ["フロントエンド", "テスト", "書籍"],
  },
  {
    path: "frontend/test/testing_techniques_and_overview.md",
    date: new Date("2024-09-18T16:18:13.000Z"),
    title: "フロントエンド開発のためのテスト入門 ~ テストの手法一覧 ~",
    tags: ["フロントエンド", "テスト", "書籍"],
  },
  {
    path: "frontend/test/ui_component_test.md",
    date: new Date("2024-09-18T16:18:13.000Z"),
    title: "フロントエンド開発のためのテスト入門 ~ テスト環境の構築 ~",
    tags: ["フロントエンド", "テスト", "書籍"],
  },
  {
    path: "infrastructure/aws/dynamodb.md",
    date: new Date("2024-09-18T16:18:13.000Z"),
    title: "DynamoDB 概要",
    tags: ["AWS", "DynamoDB"],
  },
  {
    path: "infrastructure/aws/loadBalancer.md",
    date: new Date("2024-09-18T16:18:13.000Z"),
    title: "ALB Tips",
    tags: ["AWS", "ALB", "Tips"],
  },
  {
    path: "lang/Golang/ATourOfGo/flow-control-statements.md",
    date: new Date("2024-09-18T16:18:13.000Z"),
    title: "A Tour Of Go の Flow control statements のメモ",
    tags: ["Go"],
  },
  {
    path: "lang/Golang/ATourOfGo/methods-and-interfaces.md",
    date: new Date("2024-09-18T16:18:13.000Z"),
    title: "A Tour Of Go の  Methods and Interfaces",
    tags: ["Go"],
  },
  {
    path: "lang/Golang/ATourOfGo/more-types.md",
    date: new Date("2024-09-18T16:18:13.000Z"),
    title: "A Tour Of Go の  More types",
    tags: ["Go"],
  },
  {
    path: "lang/Golang/ATourOfGo/packages-variables-functions.md",
    date: new Date("2024-09-18T16:18:13.000Z"),
    title: "A Tour Of Go の  Packages, variables, and functions",
    tags: ["Go"],
  },
  {
    path: "lang/Golang/LearningGo/Chapter1.md",
    date: new Date("2024-09-18T16:18:13.000Z"),
    title: "初めてのGo言語 ~ Chapter1 ~",
    tags: ["Go"],
  },
  {
    path: "lang/Golang/LearningGo/Chapter2.md",
    date: new Date("2024-09-18T16:18:13.000Z"),
    title: "初めてのGo言語 ~ Chapter2 ~",
    tags: ["Go"],
  },
  {
    path: "lang/Golang/LearningGo/Chapter3.md",
    date: new Date("2024-09-18T16:18:13.000Z"),
    title: "初めてのGo言語 ~ Chapter3 ~",
    tags: ["Go"],
  },
  {
    path: "lang/Golang/LearningGo/Chapter4.md",
    date: new Date("2024-09-18T16:18:13.000Z"),
    title: "初めてのGo言語 ~ Chapter4 ~",
    tags: ["Go"],
  },
  {
    path: "lang/Golang/LearningGo/Chapter5.md",
    date: new Date("2024-09-18T16:18:13.000Z"),
    title: "初めてのGo言語 ~ Chapter5 ~",
    tags: ["Go"],
  },
  {
    path: "lang/JavaScript/class.md",
    date: new Date("2024-09-18T16:18:13.000Z"),
    title: "JavaScriptのClassについて",
    tags: ["JavaScript"],
  },
  {
    path: "lang/JavaScript/diffArrowFunctionAndOther.md",
    date: new Date("2024-09-18T16:18:13.000Z"),
    title: "JavaScriptのアロー関数とその他の関数の違い",
    tags: ["JavaScript"],
  },
  {
    path: "lang/JavaScript/this.md",
    date: new Date("2024-09-18T16:18:13.000Z"),
    title: "JavaScriptにおける`this`",
    tags: ["JavaScript"],
  },
  {
    path: "lang/TypeScript/type.md",
    date: new Date("2024-09-18T16:18:13.000Z"),
    title: "意外と知らない TypeScript の型",
    tags: ["TypeScript"],
  },
];

export const mockFileCommitCountMap: Record<string, number> = {
  "ai/tech_selection_tips.md": 1,
  "architecture/klearn_architecture_handson.md": 4,
  "lang/Golang/ATourOfGo/flow-control-statements.md": 2,
};
