import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import AppBar from "@/components/app-bar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/manifest.json",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${inter.className} bg-secondary/50`}>
        <AppBar />
        <div className="container mx-auto sm:px-4 px-2 bg-white min-h-screen">
          <Providers>{children}</Providers>
        </div>
      </body>
    </html>
  );
}
