name: deploy

on:
  push:
    branches:
    - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: 'ap-northeast-1'
  AWS_S3_BUCKET: 'til-viewer-app'
  SOURCE_DIR: './out'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Configure AWS credentials with IAM Role
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{env.AWS_REGION}}
        role-to-assume: ${{secrets.AWS_ROLE_ARN}}
    - name: Copy files to S3
      run: aws s3 sync ${{env.SOURCE_DIR}} s3://${{env.AWS_S3_BUCKET}}/'
